### ISSUE TITLE
Install OBItools

### ISSUE THREAD

**Issue by hmoral** [The-Bioinformatics-Group/Albiorix#108]
I was hoping get OBItools (http://metabarcoding.org/obitools/doc/welcome.html) installed on Albiorix, please?

I tried and got the following error:
```OBITools-1.2.11/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    serenity=serenity_mode(PACKAGE,VERSION)
  File "distutils.ext/obidistutils/serenity/__init__.py", line 109, in serenity_mode
    serenity_snake(args.virtual,package,version)
  File "distutils.ext/obidistutils/serenity/__init__.py", line 58, in serenity_snake
    virtualpython=serenity_virtualenv(envname,package,version,minversion=minversion)
  File "distutils.ext/obidistutils/serenity/virtual.py", line 105, in serenity_virtualenv
    ok = (is_good_python27(python) and
  File "distutils.ext/obidistutils/serenity/checkpython.py", line 143, in is_good_python27
    rep = is_python27(path) and \
  File "distutils.ext/obidistutils/serenity/checkpython.py", line 41, in is_python27
    return     pythonversion >=StrictVersion("2.7") \
  File "/usr/local/packages/anaconda2/lib/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'```

**Comment by mtop** [comment]
Hi @hmoral 
I've tried all possible ways I can think of to install this program. For me it always fails with this error message:

```bash
Look for package virtualenv (>=1.11.0) : ok version 15.1.0 installed
/home/mtop/tmp/anaconda2/OBITools-1.2.11/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable /home/mtop/tmp/anaconda2/OBITools-1.2.11/bin/python is not functioning
ERROR: It thinks sys.prefix is u'/state/partition2/tmp/tmp8NCbGb/OBITools-1.2.11' (should be u'/home/mtop/tmp/anaconda2/OBITools-1.2.11')
ERROR: virtualenv is not compatible with this system or executable
Traceback (most recent call last):
  File "./get-obitools.py", line 45234, in <module>
    main()
  File "./get-obitools.py", line 45196, in main
    envactivate = open(os.path.join(virtualenvname,'bin','activate')).readlines()
IOError: [Errno 2] No such file or directory: '/home/mtop/tmp/anaconda2/OBITools-1.2.11/bin/activate'
```
I suggest you contact the developers and ask for some suggestions how to solve this.

Cheers

**Comment by hmoral** [comment]
OK, thanks for trying. I'll follow up with them, cheers
